version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
      - OMDB_API_KEY=${OMDB_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}


